# Generated by Django 4.2 on 2026-09-21 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reports", "0010_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportnote",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="Add the content of this note",
                verbose_name="Content",
            ),
        ),
        migrations.AlterField(
            model_name="reportnote",
            name="heading",
            field=models.TextField(
                help_text="Add a heading for this note", verbose_name="Heading"
            ),
        ),
        migrations.AlterField(
            model_name="reportnote",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.savedreport",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="created_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reportschedule_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which groups this report should be sent to.",
                related_name="scheduledreports",
                to="auth.group",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="last_sent",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last Sent"
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reportschedule_modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified by",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="report",
            field=models.OneToOneField(
                help_text="Select the report this schedule pertains to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="reports.savedreport",
                verbose_name="Report",
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select individual users this report should be sent to.",
                related_name="scheduledreports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified"),
        ),
        migrations.AlterField(
            model_name="savedreport",
            name="modified_by",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="report_modifier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modified",
            ),
        ),
    ]
