from django.urls import path, re_path

from qatrack.service_log import views

urlpatterns = [
    path("", views.SLDashboard.as_view(), name="sl_dash"),
    path('event/', views.ServiceEventsBaseList.as_view(), name="sl_list_all"),
    path('event/create/', views.CreateServiceEvent.as_view(), name='sl_new'),
    path('event/create/choose-unit/', views.ChooseUnitForNewSE.as_view(), name="sl_unit_new"),
    re_path(r'^event/edit(?:/(?P<pk>\d+))?/$', views.UpdateServiceEvent.as_view(), name="sl_edit"),
    re_path(r'^event/details(?:/(?P<pk>\d+))?/$', views.DetailsServiceEvent.as_view(), name="sl_details"),
    re_path(r'^event/delete(?:/(?P<pk>\d+))?/$', views.DeleteServiceEvent.as_view(), name='se_delete'),
    path('event/review-required/', views.ServiceEventsReviewRequiredList.as_view(), name="sl_list_review_required"),
    path('event/review/choose-unit/', views.ChooseUnitForViewSE.as_view(), name="sl_unit_view_se"),
    path('event/unit/<int:unit_number>/', views.ServiceEventsByUnitList.as_view(), name="sl_list_by_unit"),
    path('event/initiated-by/<int:tli_pk>/', views.ServiceEventsInitiatedByList.as_view(), name="sl_list_initiated_by"),
    path('event/return-to-service-for/<int:tli_pk>/', views.ServiceEventsReturnToServiceForList.as_view(), name="sl_list_return_to_service_for"),
    path('event/status/<int:pk>/', views.ServiceEventsByStatusList.as_view(), name="sl_list_by_status"),
    path('event/report/<int:pk>/', views.service_log_report, name="sl_service_event_report"),
    path('rtsqa/', views.ReturnToServiceQABaseList.as_view(), name="rtsqa_list_all"),
    path('rtsqa/incomplete/', views.ReturnToServiceQAIncompleteList.as_view(), name="rtsqa_list_incomplete"),
    path('rtsqa/unreviewed/', views.ReturnToServiceQAUnreviewedList.as_view(), name="rtsqa_list_unreviewed"),
    path('rtsqa/event/<int:se_pk>', views.ReturnToServiceQAForEventList.as_view(), name="rtsqa_list_for_event"),
    path('se-searcher/', views.se_searcher, name="se_searcher"),
    re_path(r'^tli-select(?:/(?P<pk>\d+))?(?:/(?P<form>[a-zA-Z0-9-_]+)/)?$', views.TLISelect.as_view(), name="tli_select"),
    path('tli-statuses/', views.tli_statuses, name="tli_statuses"),
    path('unit-sa_utc/', views.unit_sa_utc, name="unit_sa_utc"),
    path('err/', views.ErrorView.as_view(), name='err'),
    path('down-time/', views.ServiceEventDownTimesList.as_view(), name='se_down_time'),
    path('handle-unit-down-time/', views.handle_unit_down_time, name='handle_unit_down_time'),
    path('templates/create_ajax/', views.CreateServiceEventTemplateAjax.as_view(), name='create_se_template'),
    path('templates/searcher/', views.service_event_template_searcher, name='se_template_searcher'),
    path('event/schedule/all/', views.ServiceEventScheduleList.as_view(), name='se_schedule_list_all'),
    path('event/schedule/due-and-overdue/', views.DueAndOverdue.as_view(), name='se_schedule_due'),
    path('event/schedule/due-dates/', views.DueDateOverview.as_view(), name='se_schedule_overview_due_dates'),
    path('event/schedule/due-dates-user/', views.DueDateOverview.as_view(), name='se_schedule_overview_due_dates_user'),
]
