# Generated by Django 4.2 on 2026-09-21 15:34

from django.db import migrations


def delete_dead_schedule(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.filter(func='qatrack.notifications.service_log_scheduling.tasks.run_service_event_scheduling_notices').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0026_v4_0_final'),
        ('django_q', '0019_alter_task_options_alter_ormq_key_alter_ormq_lock_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_dead_schedule, migrations.RunPython.noop),
    ]
