# Generated by Django 4.2 on 2026-09-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("units", "0021_v4_0_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Set to false if unit is no longer in use",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="install_date",
            field=models.DateField(
                blank=True,
                help_text="Optional install date",
                null=True,
                verbose_name="install date",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_serviceable",
            field=models.BooleanField(
                default=True,
                help_text="Set to true to enable this unit to be selectable in service events",
                verbose_name="is serviceable",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Optional location information",
                max_length=256,
                null=True,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(
                help_text="The display name for this unit",
                max_length=256,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="A unique number for this unit. Leave blank to have it assigned automatically",
                unique=True,
                verbose_name="number",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Optional serial number",
                max_length=256,
                null=True,
                verbose_name="serial number",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="date_changed",
            field=models.DateField(
                blank=True,
                help_text="Date the units available time changed or will change",
                verbose_name="Date Changed",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_friday",
            field=models.DurationField(
                help_text="Duration of available time on Fridays",
                verbose_name="Hours Friday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_monday",
            field=models.DurationField(
                help_text="Duration of available time on Mondays",
                verbose_name="Hours Monday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_saturday",
            field=models.DurationField(
                help_text="Duration of available time on Saturdays",
                verbose_name="Hours Saturday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_sunday",
            field=models.DurationField(
                help_text="Duration of available time on Sundays",
                verbose_name="Hours Sunday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_thursday",
            field=models.DurationField(
                help_text="Duration of available time on Thursdays",
                verbose_name="Hours Thursday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_tuesday",
            field=models.DurationField(
                help_text="Duration of available time on Tuesdays",
                verbose_name="Hours Tuesday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="hours_wednesday",
            field=models.DurationField(
                help_text="Duration of available time on Wednesdays",
                verbose_name="Hours Wednesday",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletime",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="units.unit",
                verbose_name="unit",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="date",
            field=models.DateField(
                help_text="Date of available time change", verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="hours",
            field=models.DurationField(
                help_text="New duration of availability", verbose_name="hours"
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="A quick name or reason for the change",
                max_length=64,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="unitavailabletimeedit",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="units.unit",
                verbose_name="unit",
            ),
        ),
    ]
