# Generated by Django 4.2 on 2026-06-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0059_Auto_BigAuto_TimeZone_Django42"),
        ("faults", "0014_Auto_BigAuto_TimeZone_Django42"),
        ("service_log", "0027_Auto_BigAuto_TimeZone_Django42"),
        ("issue_tracker", "0016_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"verbose_name": "Issue", "verbose_name_plural": "Issues"},
        ),
        migrations.AlterModelOptions(
            name="issuepriority",
            options={
                "ordering": ("order",),
                "verbose_name": "Issue Priority",
                "verbose_name_plural": "Issue Priorities",
            },
        ),
        migrations.AlterModelOptions(
            name="issuestatus",
            options={
                "ordering": ("order",),
                "verbose_name": "Issue Status",
                "verbose_name_plural": "Issue Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetag",
            options={
                "ordering": ("name",),
                "verbose_name": "Issue Tag",
                "verbose_name_plural": "Issue Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetype",
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="fault_logs",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                to="faults.fault",
                verbose_name="Fault Logs",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="service_events",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                to="service_log.serviceevent",
                verbose_name="Service Events",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="test_list_instances",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                to="qa.testlistinstance",
                verbose_name="QA Submissions",
            ),
        ),
        migrations.AlterField(
            model_name="issuepriority",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="issuestatus",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="issuetype",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
