# Generated by Django 4.2 on 2026-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faults", "0015_alter_fault_options_alter_faultreviewgroup_options_and_more"),
        ("service_log", "0028_alter_grouplinker_options_and_more"),
        ("qa", "0060_alter_autoreviewrule_options_and_more"),
        ("issue_tracker", "0016_Auto_BigAuto_TimeZone_Django42"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"verbose_name": "Issue", "verbose_name_plural": "Issues"},
        ),
        migrations.AlterModelOptions(
            name="issuepriority",
            options={
                "ordering": ("order",),
                "verbose_name": "Issue Priority",
                "verbose_name_plural": "Issue Priorities",
            },
        ),
        migrations.AlterModelOptions(
            name="issuestatus",
            options={
                "ordering": ("order",),
                "verbose_name": "Issue Status",
                "verbose_name_plural": "Issue Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetag",
            options={
                "ordering": ("name",),
                "verbose_name": "Issue Tag",
                "verbose_name_plural": "Issue Tags",
            },
        ),
        migrations.AlterModelOptions(
            name="issuetype",
            options={
                "verbose_name": "Issue Type",
                "verbose_name_plural": "Issue Types",
            },
        ),
        migrations.RemoveField(
            model_name="issue",
            name="error_screen",
        ),
        migrations.AddField(
            model_name="issue",
            name="fault_logs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related Fault Logs",
                related_name="issues",
                to="faults.fault",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="qa_logs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related QA Logs",
                related_name="issues",
                to="qa.testlistinstance",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="service_events",
            field=models.ManyToManyField(
                blank=True,
                help_text="Related Service Events",
                related_name="issues",
                to="service_log.serviceevent",
            ),
        ),
        migrations.AddField(
            model_name="issuestatus",
            name="resolved",
            field=models.BooleanField(
                default=False, help_text="Is this issue considered resolved/closed?"
            ),
        ),
        migrations.AlterField(
            model_name="issuepriority",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="issuestatus",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="issuetype",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
