# Generated by Django 4.2 on 2026-06-06 17:15

from django.db import migrations


def populate_default_statuses(apps, schema_editor):
    IssueStatus = apps.get_model('issue_tracker', 'IssueStatus')

    statuses = [
        ("Ongoing", "Is an active issue under investigation", "rgba(255,255,0,1)", False, 10),
        ("Resolved", "Issue has been resolved.", "rgba(0,128,0,1)", True, 20),
        ("Retired", "Issue hasn't been resolve, but is no longer a concern.", "rgba(128,0,128,1)", True, 30),
    ]

    for name, description, colour, resolved, preferred_order in statuses:
        if not IssueStatus.objects.filter(name=name).exists():
            while IssueStatus.objects.filter(order=preferred_order).exists():
                preferred_order += 10
            
            IssueStatus.objects.create(
                name=name,
                description=description,
                colour=colour,
                resolved=resolved,
                order=preferred_order
            )

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("issue_tracker", "0017_alter_issue_options_alter_issuepriority_options_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_default_statuses, reverse_code=noop),
    ]

