# Generated by Django 4.2 on 2026-09-21 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0061_alter_autoreviewrule_pass_fail_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("service_log", "0028_v4_0_final"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="returntoserviceqa",
            options={
                "default_permissions": ("add", "change", "delete"),
                "ordering": ["-datetime_assigned"],
                "permissions": (
                    ("view_returntoserviceqa", "Can view Return To Service QC"),
                    ("perform_returntoserviceqa", "Can perform Return To Service QC"),
                ),
                "verbose_name": "Return To Service QC",
                "verbose_name_plural": "Return To Service QC",
            },
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="service_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="service_log.serviceevent",
                verbose_name="service event",
            ),
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="test_list_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rtsqa_for_tli",
                to="qa.testlistinstance",
                verbose_name="test list instance",
            ),
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="unit_test_collection",
            field=models.ForeignKey(
                help_text="Select a TestList to perform",
                on_delete=django.db.models.deletion.CASCADE,
                to="qa.unittestcollection",
                verbose_name="unit test collection",
            ),
        ),
        migrations.AlterField(
            model_name="returntoserviceqa",
            name="user_assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user assigned by",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevent",
            name="due_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When was this service event due when it was performed",
                null=True,
                verbose_name="due date",
            ),
        ),
        migrations.AlterField(
            model_name="serviceevent",
            name="include_for_scheduling",
            field=models.BooleanField(
                default=True,
                help_text="Should this instance be considered when calculating due dates?",
                verbose_name="Include for Scheduling",
            ),
        ),
        migrations.AlterField(
            model_name="serviceeventschedule",
            name="assigned_to",
            field=models.ForeignKey(
                help_text="QC group that this test list should nominally be performed by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serviceeventschedule_assigned_to",
                to="auth.group",
                verbose_name="assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="serviceeventschedule",
            name="visible_to",
            field=models.ManyToManyField(
                help_text="Select groups who will be able to see this test collection on this unit",
                related_name="serviceeventschedule_visible_to",
                to="auth.group",
                verbose_name="visible to",
            ),
        ),
        migrations.AlterField(
            model_name="serviceeventtemplate",
            name="modified",
            field=models.DateTimeField(auto_now=True, verbose_name="modified"),
        ),
    ]
